export const EventTypeRegisterRole = "register_role"
export const AttributeKeyRole = "role"
export const AttributeKeyLabel = "label"
export const AttributeKeyContractAddress = "contract_address"
export const AttributeKeyContractAddressCreated = "contract_address_created"
